apiVersion: v1
kind: Service
metadata:
  name: nemo-guardrails
  namespace: nemo-guardrails
  labels:
    app: nemo-guardrails
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: nemo-guardrails
